"""empty message

Revision ID: 554d445e858f
Revises: 6f9f6db1f5e4
Create Date: 2021-05-09 12:04:23.658393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554d445e858f'
down_revision = '6f9f6db1f5e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cell_line_generation', sa.Column('facs_s', sa.String(length=128), nullable=True))
    op.add_column('cell_line_generation', sa.Column('pcr_s', sa.String(length=128), nullable=True))
    op.add_column('cell_line_generation', sa.Column('sequencing_info_s', sa.String(length=128), nullable=True))
    op.add_column('cell_line_generation', sa.Column('wb_s', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_cell_line_generation_facs_s'), 'cell_line_generation', ['facs_s'], unique=True)
    op.create_index(op.f('ix_cell_line_generation_pcr_s'), 'cell_line_generation', ['pcr_s'], unique=True)
    op.create_index(op.f('ix_cell_line_generation_sequencing_info_s'), 'cell_line_generation', ['sequencing_info_s'], unique=True)
    op.create_index(op.f('ix_cell_line_generation_wb_s'), 'cell_line_generation', ['wb_s'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cell_line_generation_wb_s'), table_name='cell_line_generation')
    op.drop_index(op.f('ix_cell_line_generation_sequencing_info_s'), table_name='cell_line_generation')
    op.drop_index(op.f('ix_cell_line_generation_pcr_s'), table_name='cell_line_generation')
    op.drop_index(op.f('ix_cell_line_generation_facs_s'), table_name='cell_line_generation')
    op.drop_column('cell_line_generation', 'wb_s')
    op.drop_column('cell_line_generation', 'sequencing_info_s')
    op.drop_column('cell_line_generation', 'pcr_s')
    op.drop_column('cell_line_generation', 'facs_s')
    # ### end Alembic commands ###
