"""empty message

Revision ID: 8ba9d02e1312
Revises: 554d445e858f
Create Date: 2021-05-23 19:57:13.493393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba9d02e1312'
down_revision = '554d445e858f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cell_lines', sa.Column('timeedited', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_cell_lines_timeedited'), 'cell_lines', ['timeedited'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cell_lines_timeedited'), table_name='cell_lines')
    op.drop_column('cell_lines', 'timeedited')
    # ### end Alembic commands ###
