"""added name to cell line

Revision ID: da6a74da768f
Revises: f035d99e3596
Create Date: 2020-07-30 09:27:57.285981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6a74da768f'
down_revision = 'f035d99e3596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cell_lines', sa.Column('name', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_cell_lines_name'), 'cell_lines', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cell_lines_name'), table_name='cell_lines')
    op.drop_column('cell_lines', 'name')
    # ### end Alembic commands ###
