"""chnaged to Date

Revision ID: e08f988304bf
Revises: da6a74da768f
Create Date: 2020-07-31 11:39:59.905088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e08f988304bf'
down_revision = 'da6a74da768f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cell_lines_celltype', table_name='cell_lines')
    op.create_index(op.f('ix_cell_lines_celltype'), 'cell_lines', ['celltype'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cell_lines_celltype'), table_name='cell_lines')
    op.create_index('ix_cell_lines_celltype', 'cell_lines', ['celltype'], unique=1)
    # ### end Alembic commands ###
